development:
  adapter: postgresql
  database: redmart_development

production:
   url: <%= ENV['postgres://sxgyfkvnbckdxq:nZVHNjumARwRrBBcKt1DiQ7m3p@ec2-54-163-249-150.compute-1.amazonaws.com:5432/de24ehpvmma7al
'] %>
